### ISSUE TITLE
Release notes syntax characters incorrect

### ISSUE THREAD

**Issue by GoateePFE** [PowerShell/PowerShell-Docs#120]
Topics throughout the entire WMF 5.0 release notes have text conversion issues like: &lt; &gt; \#

**Comment by HemantMahawar** [comment]
@GoateePFE  Can you give some specific examples? Or all such issues have been fixed through various updates?

**Comment by GoateePFE** [comment]
Here is what I can find at a glance today in the live published content:

https://msdn.microsoft.com/en-us/powershell/wmf/psget_module_overview

·         Has \ in front of # comment lines

·         Other files in this section of the release notes have the same issue

https://msdn.microsoft.com/en-us/powershell/wmf/psget_modulesxsinstall

·         Escaped backslashes and HTML code for >

·         PS C:\\windows\\system32&gt; Install-Module -Name PSScriptAnalyzer -RequiredVersion 1.1.0 -Repository PSGallery

·         Other files in this section of the release notes have the same issue

https://msdn.microsoft.com/en-us/powershell/wmf/psget_modulecmdlets

·         **Find-DscResource** \[\[-Name\] &lt;string\[\]&gt;\] \[-ModuleName &lt;string&gt;\] \[-MinimumVersion &lt;version&gt;\] \[-RequiredVersion &lt;version&gt;\] \[-AllVersions\] \[-Tag &lt;string\[\]&gt;\] \[-Filter &lt;string&gt;\] \[-Repository &lt;string\[\]&gt;\] \[&lt;CommonParameters&gt;\]

·         Looks like a combination of markdown and HTML rendering in the code section.

As I look through the release notes these issues surface on multiple articles.

**Comment by HemantMahawar** [comment]
@GoateePFE   Thanks for pointing out the specifics ... I can see them now too :). We will get it fixed. @JKeithB

**Comment by joeyaiello** [comment]
Got a joeyScrub branch I'm operating out of for a bunch of this stuff. Going through a ton of files to get 'em cleaned up. Rebased off of all your work, Hemant, so nothing lost there. :)

**Comment by HemantMahawar** [comment]
@GoateePFE Made some fixed with #153, #154, #155, #156, #157 ... which are live with #158.

@KrishnaV-MSFT @JKeithB @jianyunt @xumins ... There is still some cleanup needed in [odata_overview.md](https://github.com/PowerShell/PowerShell-Docs/blob/master/wmf/odata_overview.md), [oneget_cmdlets.md](https://github.com/PowerShell/PowerShell-Docs/blob/master/wmf/oneget_cmdlets.md), [psget_moduledependency.md](https://github.com/PowerShell/PowerShell-Docs/blob/master/wmf/psget_moduledependency.md), [psget_module_overview.md](https://github.com/PowerShell/PowerShell-Docs/blob/master/wmf/psget_module_overview.md), [psget_psrepository.md](https://github.com/PowerShell/PowerShell-Docs/blob/master/wmf/psget_psrepository.md), [psget_scriptcmdlets.md](https://github.com/PowerShell/PowerShell-Docs/blob/master/wmf/psget_scriptcmdlets.md) FYI for @joeyaiello

**Comment by DonGill** [comment]
Not sure if this was resolved. Capturing in OneView TFS ([46624](http://vstfcsd:8080/tfs/CSI/OneView/_workitems#id=46624&fullScreen=false&_a=edit)).

**Comment by juanpablojofre** [comment]
Closed as per VSTS #46624 status: Fixed and reviewed.
