### ISSUE TITLE
Convert-String has incorrect example 

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/PowerShell-Docs#1257]
Issue Details
-----------------
see #1236 : example #1 of convert-string.MD doesn't work 
```powershell
Convert-String -InputObject $Names -Example "Patti Fuller = Fuller, P."
```
```
Convert-String : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'InputObject'.
Specified method is not supported.
At line:1 char:29
+ Convert-String -InputObject $Names -Example "Patti Fuller = Fuller, P ...
+                             ~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Convert-String], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgument,Microsoft.PowerShell.Commands.StringManipulation.ConvertStringComm
   and
```

> '-InputObject' usually doesn't take a list, and you can't have blanks around the '=' sign.

PS> $Names | Convert-String -Example "Patti Fuller=Fuller, P."
Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by juanpablojofre** [comment]
@zjalexander, jszabo98,

I have to disagree with the suggested fix.

The syntax for `Convert-String` is:

```syntax
Convert-String [-Example <System.Collections.Generic.List`1[System.Management.Automation.PSObject]>]
 -InputObject <String> [<CommonParameters>]
```

Which clearly states that `-InputObject` can take a simple string, not an array of strings. Hence, the error message of **Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'InputObject'.**

The reason why the following sample works:
```powershell
"Mu Han", "Jim Hance", "David Ahs", "Kim Akers" | Convert-String -Example "Ed Wilson=Wilson, E."
```
Is because through the pipeline the array is converted to single elements that are *PROCESS*ed by the `Convert-String`, one string at a time.

Best regards,
-- JP

**Comment by jszabo98** [comment]
I don't understand the disagreement?

The text under example 1 needs to be cleaned up a bit.  By the way, under the '-example' parameter, it says:

"Patti Fuller = Fuller, P."

which won't work because of the spaces around the '=' sign.

**Comment by juanpablojofre** [comment]
@jszabo98,
If the issue is about the `-InputObject` argument not taking arrays, then the complain should be dropped. Because the BNF for this cmdlet clearly states that it takes no arrays, and the error message given is correct.

If the issue is about the description under the `-Example` heading, then a clarification needs to be made to indicate the string to the left of the `=` sign must be an exact match of the pattern elements.

This following code works pretty fine with the given example in the documentation.

```powershell
$data = "Antonio Vivaldi 1678-1741", "Franz Liszt 1811-1886", "Dmitri Shostakovich 1906-1975", "JS Bach 1685-1750"
$data | Convert-String -Example "Patti Fuller = Fuller, P."
```
```output
 Vivaldi, A.
 Liszt, F.
 Shostakovich, D.
 Bach, J.
```

Please note there is a leading space in each line of the output, as per the `-Example`.

**Comment by jszabo98** [comment]
I didn't say -inputobject should take an array.  Example 1 originally demonstrated -inputobject taking an array.

I think most people would intend something like "Patti Fuller=Fuller, P.", as shown in example 1.

**Comment by juanpablojofre** [comment]
@jszabo98,
Take a look into #1395 and let me know if you think this solves this issue.
