### ISSUE TITLE
New approved verbs

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell-Docs#1630]
https://msdn.microsoft.com/en-us/library/ms714428(VS.85).aspx needs to be updated based on
https://github.com/PowerShell/PowerShell/issues/3346

New verbs: Build and Deploy

**Comment by skfd** [comment]
Is there some other list of approved verbs other than that unupdated MSDN article?

**Comment by matt9ucci** [comment]
@skfd No, there is not, as far as I know. When I want to know what verbs are approved, I execute `Get-Verb` cmdlet. But the output contains just only short description that is not sufficient for learning the verbs.

@sdwheeler The MSDN article can not be updated by community because it does not belongs to this github repository. It might be a good idea to create an "about_Verbs.md" file or assign someone of the Microsoft PowerShell team to update the MSDN article.

**Comment by sdwheeler** [comment]
@skfd @matt9ucci @SteveL-MSFT We are in the process of migrating the remaining documentation from MSDN to the new docs platform. We really don't have a way to update that content until we migrate it. What we may be able to do is redirect the MSDN URL to a newer article on docs.
