### ISSUE TITLE
PackagemanagementSource fails with error message "The parameter 'Location' is required for this operation."

### ISSUE THREAD

**Issue by yvesgermain** [PowerShell/PowerShell-Docs#2381]
The DSC module PackageManagementSource fails with error message 
Issue Details
-----------------
PS C:\> Invoke-DscResource -Method Set -ModuleName PackageManagement -name PackageManagementSource -Property @{ Ensure = "Present" ; Name = "PSGallery" ; ProviderName = "NuGet" ; SourceLocation = "https://www.powershellgallery.com/api/v2/package";  InstallationPolicy = "Trusted"} -Verbose
COMMENTAIRES : Effectuez l'opération « Invoquer une méthode CIM » avec les paramètres suivants : « 'methodName' = ResourceSet,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' =
root/Microsoft/Windows/DesiredStateConfiguration ».
COMMENTAIRES : Un appel de méthode du Gestionnaire de configuration local est arrivé de l'ordinateur SQL2014 avec le SID utilisateur S-1-5-21-3870431404-4102892703-1469835163-1769.
COMMENTAIRES : [SQL2014]:                            [DSCEngine] Importation du module C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.1.7.0\DscResources\MSFT_PackageManagementSource\MSFT_PackageManagementSource.psm1 en mode de forçage.
COMMENTAIRES : [SQL2014]: LCM:  [ Début  Définir  ]  [[PackageManagementSource]DirectResourceAccess]
COMMENTAIRES : [SQL2014]:                            [[PackageManagementSource]DirectResourceAccess] Importation du module MSFT_PackageManagementSource en mode de forçage.
AVERTISSEMENT : [SQL2014]:                            [[PackageManagementSource]DirectResourceAccess] Begin registering 'PSGallery' to source location 'https://www.powershellgallery.com/api/v2/package' with
 'Trusted' policy"
COMMENTAIRES : [SQL2014]:                            [[PackageManagementSource]DirectResourceAccess] Begin invoking Register-Packagesource PSGallery
COMMENTAIRES : [SQL2014]:                            [[PackageManagementSource]DirectResourceAccess] Acquiring providers for assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.1.7.0\fullclr\Microsoft.PackageManagement.ArchiverProviders.dll
COMMENTAIRES : [SQL2014]:                            [[PackageManagementSource]DirectResourceAccess] Acquiring providers for assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.1.7.0\fullclr\Microsoft.PackageManagement.CoreProviders.dll
COMMENTAIRES : [SQL2014]:                            [[PackageManagementSource]DirectResourceAccess] Acquiring providers for assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.1.7.0\fullclr\Microsoft.PackageManagement.MsuProvider.dll
COMMENTAIRES : [SQL2014]:                            [[PackageManagementSource]DirectResourceAccess] Acquiring providers for assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.1.7.0\fullclr\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
COMMENTAIRES : [SQL2014]:                            [[PackageManagementSource]DirectResourceAccess] Acquiring providers for assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.1.7.0\fullclr\Microsoft.PackageManagement.MsiProvider.dll
COMMENTAIRES : [SQL2014]:                            [[PackageManagementSource]DirectResourceAccess] Acquiring providers for assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.1.7.0\fullclr\Microsoft.PackageManagement.NuGetProvider.dll
The parameter 'Location' is required for this operation.
    + CategoryInfo          : InvalidArgument : (Location:) [], CimException
    + FullyQualifiedErrorId : MissingRequiredParameter,Microsoft.PowerShell.PackageManagement.Cmdlets.RegisterPackageSource
    + PSComputerName        : localhost

COMMENTAIRES : [SQL2014]: LCM:  [ Fin    Définir  ]  [[PackageManagementSource]DirectResourceAccess]  en 2.6250 secondes.
La ressource DSC PowerShell MSFT_PackageManagementSource n'a pas pu exécuter la fonctionnalité Set-TargetResource. Message d'erreur: Failed to register the package source PSGallery.
Message:System.Exception: The parameter 'Location' is required for this operation.
    + CategoryInfo          : InvalidOperation : (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

COMMENTAIRES : L'opération « Invoquer une méthode CIM » est terminée.
COMMENTAIRES : Le temps nécessaire à l'exécution de la tâche de configuration est de 3.064 secondes

Version(s) of document impacted
------------------------------
PS C:\> get-dscresource -name PackageManagementSource

ImplementedAs   Name                      ModuleName                     Version    Properties
-------------   ----                      ----------                     -------    ----------
PowerShell      PackageManagementSource   PackageManagement              1.1.7.0    {Name, ProviderName, SourceLocation, DependsOn...}

----------------------------------------------------
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by sdwheeler** [comment]
@mgreenegit Can you triage and assign this as appropriate?

**Comment by DCtheGeek** [comment]
I was able to repro this.

The PackageManagementSource DSC Resource has a special case when working with a source name of 'PSGallery'.  In this event, it uses `Get-PackageSource` to check to see if the source already exists.  If it does, it uses `Set-PSRepository` to update it; if it doesn't, then it removes 'Location' (since it's known and will default) and registers via `Register-PackageSource`.  The actual error message above is "The parameter 'Location' is required for this operation.", which is confusing because that isn't a required parameter on the DSC Resource.  Internal to the DSC Resource, SourceLocation is stored as Location and if 'PSGallery' was the name, but didn't exist, it removes that and tries to creates a clean one.  Hence, the confusing error message.

Based on my tests, I'm willing to bet that in your environment 'PSGallery' actually does exist. But the resource fails to match it because it does a complete match using Name, Source Location, and Provider.  While Name matches up, your Invoke is passing a different source location (which should be "https://www.powershellgallery.com/api/v2/", drop the "package") and a different provider (which should be "PowerShellGet" instead of "NuGet").  You can see this is likely already on your system using `Get-PSRepository` or `Get-PackageSource`.

Making those changes should get your `Invoke-DscResource` working.  Also consider updating to the latest version of those resources (1.1.7.2) via the PowerShell Gallery.  I've also created PR #2491 to address the fact that the property names changed at some point.

@sdwheeler Once you've reviewed/merged PR #2491, this issue can probably be closed.

**Comment by sdwheeler** [comment]
PR #2491 merged - closing this issue. Changes will go live later this week.
