### ISSUE TITLE
Pull server protocol spec

### ISSUE THREAD

**Issue by aL3891** [PowerShell/PowerShell-Docs#398]
Is the pull server protocol currently documented somewhere? It would ve very useful to have it when implementing a custom pull server.

**Comment by ArieHein** [comment]
Nope.
We all wish it was to some degree so we can do customization but at the moment from everything we know they are not ready to go open about the protocol. 

Theres a highly supported user voice for MS to go open source on the pull server (under the hoods its basically a dll).

**Comment by aL3891** [comment]
aw shucks :/ I started to reverse engineer (by using a blank web app and see what requests it gets) but that project has fallen behind a little.. really wish they'd release the spec as it doesn't seem very big and also the current pull server has some severe limitations

**Comment by ArieHein** [comment]
I think it would be more logical to expect a way to extend but I dont think it will ever go full OSS.
If DSC is a core process for an enterprise, MS is likely to want to keep that under her wings as it will play a major role in support tickets that people open afterwards just because it was OSS and they "played" with the building blocks and something isn't working now.

**Comment by HemantMahawar** [comment]
DSC Pull Protocol [MS-DSCPM] is documented at https://msdn.microsoft.com/en-us/library/dn393548.aspx ... I believe it is up2date for WMF 5 RTM. cc @grayzu @nanalakshmanan

**Comment by grayzu** [comment]
It is up to date with changes made to WMF 5 RTM. @ArieHein @aL3891  Let us know if you have any questions or run into any issues with it.

MarkG

**Comment by aL3891** [comment]
Awesome, thanks!
