### ISSUE TITLE
DSC web pull server recommendations

### ISSUE THREAD

**Issue by sameer-kumar** [PowerShell/PowerShell-Docs#567]
In my on-prem TFS 2015 environment we are starting with Release Management. I'm setting up a new node for installing RM agents for deployments. Can I use the same node as DSC pull server (web based)?
Or the recommendation is to have it on seperate exclusive web node?

Thanks for your help!
Sam

**Comment by ArieHein** [comment]
There's no relations between on what node you install the TFS 2015 BUILD/RM agents and what other roles you want to apply to that node. 
The pull server is an endpoint so basically a webserver listening on a port. As long as you don't bind that port to a different webserver you install on that node,  or use the endpoint name for a website, or use an application pool name similar to that of the pull server there shouldn't be any issue, but then neither of the points I mentioned has any relations to the Agents.

**Comment by sameer-kumar** [comment]
Cool! Anything from performance standpoint? Is DSC web pull server resource hungry? Do both these capabilities (RM agents and pull server) compete for resources?

Thanks!

**Comment by ArieHein** [comment]
I'd say its not a resource hungry feature, depending on how many nodes you want to connect to one pull server as the bottleneck would actually be the local database that resides on the pull server. One of the bugs in WMF 5.0 that was fixed in WMF 5.1 deals with node registration failing on the database level, but overall its not different then having an IIS with multiple websites.
The other thing that controls this is how frequent you set the LCM on each of the nodes to contact the pull server. While the minimum is 15 min, it doesn't have to be set to that.

Do note that if you are using the ReportServer option and you place it on the same pull server, then the communication with the pull server will increase. So if you have multiple nodes all connected to the same pull server and then use it as a DSC ReportServer, you will see increase in traffic.
This is one of the reasons I would split Prod server from other servers into two distinct pull servers and use a third server as the ReportServer as they are all just existing IIS servers I have, but if you're limited in servers, you can have them all in one place.

**Comment by sameer-kumar** [comment]
Cool! Thanks.

**Comment by eslesar** [comment]
@sameer-kumar  and @ArieHein Thank you for the discussion. Closing this issue as it looks like it was answered.
