### ISSUE TITLE
Errors while creating new DSC pull server

### ISSUE THREAD

**Issue by sameer-kumar** [PowerShell/PowerShell-Docs#572]
I'm trying to create a new DSC web pull server following the sample scripts provided at
https://github.com/PowerShell/Whitepapers/blob/master/PullServerCPIG/PullServerCPIG.md

However, I get access denied errors for **ModulePath** and **ConfigurationPath** values as specified under **xDSCWebService** PSDSCPullServer resource. These values are network shared UNC path.

```
Job {A3B56321-5DA6-11E6-810C-005056A73C79} : 
This event indicates that a non-terminating error was thrown when DSCEngine was executing Set-TargetResource on MSFT_xDSCWebService DSC resource. FullyQualifiedErrorId is CreateDirectoryUnauthorizedAccessError,Microsoft.PowerShell.Commands.NewItemCommand. Error Message is Access to the path '<UNCpath>' is denied..
```

I guess (may be I'm wrong), the security context under which this configuration triggered is different from my domain login account. Is there a way I can specify PSCredentials object while executing the DscConfiguration as described in the sample provided in the link?

If I comment out the path, the next error is:

```
Exception calling "GetSection" with "2" argument(s): "Filename: \\?\UNC\dom.intranet\dfs-user$\user3\My Documents\IISExpress\config\applicationHost.config
Error: Unrecognized configuration path 'MACHINE/WEBROOT/APPHOST/PSDSCPullServer'
```
Is this resource buggy?

Thanks for your help!

**Comment by ArieHein** [comment]
You can not place those on a shared drive, they have to be local as the DSC service runs on system account and thus has no permissions to go to network resource and you cant change it

**Comment by sameer-kumar** [comment]
So if I have 10 pull servers in my environment, I need to copy artifacts onto these servers locally. In my opinion it's an overhead and an extra task. Is it recommended approach?

**Comment by ArieHein** [comment]
Its not a question of recommended approach unfortunately. Its how the technology works at this moment and if there isn't an opened UserVoice issue about this, here's your chance to open one and I'm sure others will upvote it.

I doubt you need 10, but if you do have a good number of pull servers its because you have to deploy either to different disconnected environments (behind firewalls for example) in which case you would have to copy things to those environments anyway as you wouldn't get ports opened between the nodes and the pull server. Perhaps dedicated servers would help if you fear congestion or 

You only need to "copy" artifacts to the pull servers serving nodes that need those artifacts, so its not like a "blind-copy-all-to-everywhere". If you want all your pull servers to hold copies of all existing artifacts just for the sake of swapping a LCM from one pull server to the other, then yes you will need to copy them. 

You can somewhat bypass the ModulePath as each node when its running the mof and deciding which DSC modules It needs then follows the normal search path of $env:PSModulePath and since that's an environment variable, you can add a UNC path to a share holding just the DSC modules on each node and they will then know where to take them from but that will cause a LOT of traffic and delays when you open PowerShell console on those nodes so I definitely not advise that for production servers and for some limited time in test/dev

**Comment by sameer-kumar** [comment]
Thanks for the clarification! Very useful.

**Comment by eslesar** [comment]
@ArieHein, @sameer-kumar thanks for the discussion! Closing this issue, as the questions appear to be answered.

**Comment by Burbert** [comment]
Hello, I've added a new module to the module folder and only for the new one I get access denied.

**Comment by ArieHein** [comment]
@Burbert should probably open a new issue with more information then revive this closed issue.
Advise to also use powershell.org forums for more answers ;)
