### ISSUE TITLE
#Requires -Module works also inside function (not doc'd)

### ISSUE THREAD

**Issue by it-praktyk** [PowerShell/PowerShell-Docs#961]
The #Requires -Module statement works also when the statement is inside function - like ilustrated on the screenshot below.

![test-requires](https://cloud.githubusercontent.com/assets/4910261/22042338/eaf6a7ba-dd0a-11e6-9afa-7ece74181134.jpg)

Help [about_Requires](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Requires.md) states:

> You can use #Requires statements in any script. You cannot use them in functions, cmdlets, or snap-ins.

**Comment by zjalexander** [comment]
We should be touching this doc as part of PS6 release, let's clean this up while we are there.

**Comment by sdwheeler** [comment]
@joeyaiello @zjalexander The current docs say: 'You cannot use them in functions, cmdlets, or snap-ins.'

Who can verify the actual rules for where #requires can be used? And did this change in some version (e.g. cannot be done in v3, can in v4+)?

**Comment by sdwheeler** [comment]
@joeyaiello @zjalexander Can we get someone to clarify how this works so we can update the docs?

**Comment by rjmholt** [comment]
I've just been looking at and tracing the execution of this behaviour in the following PowerShell version:
```
Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1-279-gf7c2b7def1cf7428dbd66c018b6fb23ef6a1c68d
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

`#requires` annotations [are collected as the script is parsed for the first time](https://github.com/PowerShell/PowerShell/blob/942832c13a3c325851e9873bd25036775c85a18c/src/System.Management.Automation/engine/parser/tokenizer.cs#L1344), and parsing continues as normal irrespective of where the `#requires` occurs or whether it should succeed. All occurrences of `#requires` in a script [are then bundled as a top-level property of the `Ast` object](https://github.com/PowerShell/PowerShell/blob/942832c13a3c325851e9873bd25036775c85a18c/src/System.Management.Automation/engine/parser/Parser.cs#L191) that represents that parsed script. Then the parser performs all semantic and type checking. **This means the `#require` annotations are effectively hoisted, no matter where they occur in a script**.

When the script gets called, the command processor checks the requirements attached to the AST and decides whether or not to proceed. Note that it's only when a script is actually invoked that [the requirements are checked](https://github.com/PowerShell/PowerShell/blob/942832c13a3c325851e9873bd25036775c85a18c/src/System.Management.Automation/engine/CommandDiscovery.cs#L357) (done [here](https://github.com/PowerShell/PowerShell/blob/942832c13a3c325851e9873bd25036775c85a18c/src/System.Management.Automation/engine/CommandDiscovery.cs#L443)).

This behaviour strikes me as a bit strange, only because we should probably be forcing the `#require` annotations to be at the top of the script and reject parsing otherwise. So I'm going to open an RFC that addresses this and adds a couple of other suggestions.

Related: #694, [PowerShell #5022](https://github.com/PowerShell/PowerShell/issues/5022), [PowerShell #2846](https://github.com/PowerShell/PowerShell/issues/2846), [PowerShell #3751](https://github.com/PowerShell/PowerShell/issues/3751), [PowerShell #3803](https://github.com/PowerShell/PowerShell/issues/3803), [PowerShell #4549](https://github.com/PowerShell/PowerShell/issues/4549).

Thanks to @sdwheeler for collecting all these issues.

Also /cc @lzybkr and @BrucePay, who may be able to offer more insight or corrections into how `#require` works and is intended to work.

**Comment by rjmholt** [comment]
I've opened [an RFC](https://github.com/PowerShell/PowerShell-RFC/pull/122) on updating the behaviour of `#requires`. Please feel free to comment in the PR.

**Comment by sdwheeler** [comment]
Update documentation to reflect current behavior in PR #2576
